<html>
   <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>VIDEOCLUB - IES Leonardo Da Vinci - Alquiler Películas</title>
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    </head>



   <body>
    <h1 class="text-center"> VIDEOCLUB IES LEONARDO DA VINCI</h1>

    <div class="container ">
        <!--Aplicacion-->
		<div class="card border-success mb-3" style="max-width: 30rem;">
		<div class="card-header">Alquiler Películas</div>
		<div class="card-body">


	<!-- INICIO DEL FORMULARIO -->
	<form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="post">
    <?php
    //contenido de la cookie
    // $cookie=$idcliente."#".$nombrecliente."#".$apellidocliente."#".$emailcliente;
    $cookie=$_COOKIE['usuario'];
    $cookiedividida=explode("#",$cookie);
     var_dump($cookie);
    ?>
    <B>Nombre Cliente: </B>
    <?php
    echo $cookiedividida[1]." ".$cookiedividida[2];
    ?>
    <BR>
      <B>Email Cliente: </B>
      <?php
      echo $cookiedividida[3];
      ?>
      <BR>
        <B>Número Socio: </B>
        <?php
        echo $cookiedividida[0];
        ?>
        <BR><BR>
		<label for="pelicula"><B>Selecciona pelicula: </B></label>
		<select name="pelicula" class="form-control">
      <?php foreach ($desplegable->fetchAll() as $row) { ?>
        <option value="<?php echo $row["film_id"]."-".$row["title"]; ?>"><?php echo $row["title"];?></option>
      <?php } ?>
		</select>
    <br><br>
		<div>
			<input type="submit" value="Agregar a Cesta" name="agregar" class="btn btn-warning disabled">
			<input type="submit" value="Realizar Alquiler" name="alquilar" class="btn btn-warning disabled">
			<input type="submit" value="Vaciar Cesta" name="vaciar" class="btn btn-warning disabled">
      <input type="button" value="Volver" name="volver" onclick="window.location.href='../controllers/controller_aqlwelcome.php'" class="btn btn-warning disabled"><BR>

		</div>

	</form>
	<!-- FIN DEL FORMULARIO -->
	</div>
  </div>



</body>
</html>
