<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>VIDEOCLUB - IES Leonardo Da Vinci</title>
  <link rel="stylesheet" href="../css/bootstrap.min.css">
</head>
<body>
  <h1 class="text-center"> VIDEOCLUB IES LEONARDO DA VINCI</h1>
  <div class="container ">
    <!--Aplicacion-->
    <div class="card border-success mb-3" style="max-width: 30rem;">
      <div class="card-header">Menú Usuario</div>
      <div class="card-body">
        <?php
        //contenido de la cookie
        // $cookie=$idcliente."#".$nombrecliente."#".$apellidocliente."#".$emailcliente;
        $cookie=$_COOKIE['usuario'];
        $cookiedividida=explode("#",$cookie);
         var_dump($cookie);
        ?>
        <B>Nombre Cliente: </B>
        <?php
        echo $cookiedividida[1]." ".$cookiedividida[2];
        ?>
        <BR>
          <B>Email Cliente: </B>
          <?php
          echo $cookiedividida[3];
          ?>
          <BR>
            <B>Número Socio: </B>
            <?php
            echo $cookiedividida[0];
            ?>
            <BR><BR>
              <!--Formulario con botones -->
              <input type="button" value="Alquilar Películas" onclick="window.location.href=' ../controllers/controller_alqpel.php'" class="btn btn-warning disabled">
              <input type="button" value="Consultar Alquileres" onclick="window.location.href=' ../controllers/controller_alqcons.php'" class="btn btn-warning disabled">
              <input type="button" value="Devolver Películas" onclick="window.location.href=' ../controllers/controller_alqdev.php'" class="btn btn-warning disabled"><BR>
                <input type="button" value="Volver" onclick="window.location.href='../index.php'" class="btn btn-warning disabled"><BR>
                  <BR><a href="../index.php">Cerrar Sesión</a>
                  </div>
                </body>
                </html>
